-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [backfill_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace backfill_core

/-- [backfill_core::Header]
    Source: 'common/backfill_core/src/lib.rs', lines 43:0-47:1
    Visibility: public -/
structure Header where
  root : Std.U64
  parent_root : Std.U64
  slot : Std.U64

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Header}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 42:9-42:14
    Visibility: public -/
def Header.Insts.CoreCloneClone.clone (self : Header) : Result Header := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 42:9-42:14 -/
@[reducible]
def Header.Insts.CoreCloneClone : core.clone.Clone Header := {
  clone := Header.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 42:16-42:20 -/
@[reducible]
def Header.Insts.CoreMarkerCopy : core.marker.Copy Header := {
  cloneInst := Header.Insts.CoreCloneClone
}

/-- Trait implementation: [backfill_core::{impl core::marker::StructuralPartialEq for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 42:22-42:31 -/
@[reducible]
def Header.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Header := {
}

/-- [backfill_core::{impl core::cmp::PartialEq<backfill_core::Header> for backfill_core::Header}::eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 42:22-42:31
    Visibility: public -/
def Header.Insts.CoreCmpPartialEqHeader.eq
  (self : Header) (other : Header) : Result Bool := do
  if self.root = other.root
  then
    if self.parent_root = other.parent_root
    then ok (self.slot = other.slot)
    else ok false
  else ok false

/-- Trait implementation: [backfill_core::{impl core::cmp::PartialEq<backfill_core::Header> for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 42:22-42:31 -/
@[reducible]
def Header.Insts.CoreCmpPartialEqHeader : core.cmp.PartialEq Header Header := {
  eq := Header.Insts.CoreCmpPartialEqHeader.eq
}

/-- [backfill_core::{impl core::cmp::Eq for backfill_core::Header}::assert_fields_are_eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 42:33-42:35
    Visibility: public -/
def Header.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Header) : Result Unit := do
  ok ()

/-- Trait implementation: [backfill_core::{impl core::cmp::Eq for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 42:33-42:35 -/
@[reducible]
def Header.Insts.CoreCmpEq : core.cmp.Eq Header := {
  partialEqInst := Header.Insts.CoreCmpPartialEqHeader
  assert_fields_are_eq := Header.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [backfill_core::Config]
    Source: 'common/backfill_core/src/lib.rs', lines 50:0-56:1
    Visibility: public -/
structure Config where
  run_len : Std.U64
  max_attempts : Std.U8

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Config}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 49:9-49:14
    Visibility: public -/
def Config.Insts.CoreCloneClone.clone (self : Config) : Result Config := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Config}]
    Source: 'common/backfill_core/src/lib.rs', lines 49:9-49:14 -/
@[reducible]
def Config.Insts.CoreCloneClone : core.clone.Clone Config := {
  clone := Config.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Config}]
    Source: 'common/backfill_core/src/lib.rs', lines 49:16-49:20 -/
@[reducible]
def Config.Insts.CoreMarkerCopy : core.marker.Copy Config := {
  cloneInst := Config.Insts.CoreCloneClone
}

/-- [backfill_core::Wait]
    Source: 'common/backfill_core/src/lib.rs', lines 62:0-72:1
    Visibility: public -/
@[discriminant isize]
inductive Wait where
| Idle : Wait
| Pending : Wait
| Importing : Header → Std.U32 → Wait
| Parked : Wait

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Wait}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 61:9-61:14
    Visibility: public -/
def Wait.Insts.CoreCloneClone.clone (self : Wait) : Result Wait := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Wait}]
    Source: 'common/backfill_core/src/lib.rs', lines 61:9-61:14 -/
@[reducible]
def Wait.Insts.CoreCloneClone : core.clone.Clone Wait := {
  clone := Wait.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Wait}]
    Source: 'common/backfill_core/src/lib.rs', lines 61:16-61:20 -/
@[reducible]
def Wait.Insts.CoreMarkerCopy : core.marker.Copy Wait := {
  cloneInst := Wait.Insts.CoreCloneClone
}

/-- [backfill_core::Backfill]
    Source: 'common/backfill_core/src/lib.rs', lines 74:0-85:1
    Visibility: public -/
structure Backfill where
  cfg : Config
  frontier : Header
  target_slot : Std.U64
  attempts : Std.U8
  wait : Wait
  last_bad : Option Std.U32
  done : Bool

/-- [backfill_core::Event]
    Source: 'common/backfill_core/src/lib.rs', lines 90:0-97:1
    Visibility: public -/
@[discriminant isize]
inductive Event where
| Tick : Event
| Run : Std.U32 → alloc.vec.Vec Header → Event
| Fail : Std.U32 → Event
| Imported : Event
| Rejected : Event
| PeerJoined : Event

/-- [backfill_core::Action]
    Source: 'common/backfill_core/src/lib.rs', lines 99:0-112:1
    Visibility: public -/
@[discriminant isize]
inductive Action where
| Request : Std.U64 → Std.U64 → Option Std.U32 → Action
| Store : alloc.vec.Vec Header → Action
| Penalize : Std.U32 → Action
| Complete : Action

/-- [backfill_core::check_run]: loop 0:
    Source: 'common/backfill_core/src/lib.rs', lines 126:4-135:5
    Visibility: public -/
@[rust_loop]
def check_run_loop
  (headers : alloc.vec.Vec Header) (linked : Bool) (want : Std.U64)
  (limit : Std.U64) (last : Option Header) (i : Std.Usize) :
  Result (Bool × (Option Header))
  := do
  let i1 := alloc.vec.Vec.len headers
  if i < i1
  then
    let header ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Header)
        headers i
    let i2 ← i + 1#usize
    check_run_loop headers ((linked && (header.root = want)) && (header.slot <
      limit)) header.parent_root header.slot (some header) i2
  else ok (linked, last)
partial_fixpoint

/-- [backfill_core::check_run]:
    Source: 'common/backfill_core/src/lib.rs', lines 120:0-137:1
    Visibility: public -/
def check_run
  (expected : Std.U64) (bound : Std.U64) (headers : alloc.vec.Vec Header) :
  Result (Option Header)
  := do
  let (linked, last) ←
    check_run_loop headers true expected bound none 0#usize
  if linked
  then ok last
  else ok none

/-- [backfill_core::retry]:
    Source: 'common/backfill_core/src/lib.rs', lines 142:0-150:1
    Visibility: public -/
def retry (bf : Backfill) : Result Backfill := do
  if bf.attempts > 1#u8
  then
    let i ← bf.attempts - 1#u8
    ok { bf with attempts := i, wait := Wait.Idle }
  else ok { bf with attempts := 0#u8, wait := Wait.Parked }

/-- [backfill_core::on_tick]:
    Source: 'common/backfill_core/src/lib.rs', lines 152:0-171:1
    Visibility: public -/
def on_tick (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle =>
    if bf.done
    then ok (alloc.vec.Vec.new Action, bf)
    else
      let out ←
        alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Request
          bf.frontier.parent_root bf.cfg.run_len bf.last_bad)
      ok (out, { bf with wait := Wait.Pending })
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_run]:
    Source: 'common/backfill_core/src/lib.rs', lines 173:0-198:1
    Visibility: public -/
def on_run
  (bf : Backfill) (peer : Std.U32) (headers : alloc.vec.Vec Header) :
  Result ((alloc.vec.Vec Action) × Backfill)
  := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending =>
    let checked ← check_run bf.frontier.parent_root bf.frontier.slot headers
    match checked with
    | none =>
      let out ←
        alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Penalize peer)
      let bf1 ← retry { bf with last_bad := (some peer) }
      ok (out, bf1)
    | some oldest =>
      let out ←
        alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Store headers)
      ok (out, { bf with wait := (Wait.Importing oldest peer) })
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_imported]:
    Source: 'common/backfill_core/src/lib.rs', lines 203:0-221:1
    Visibility: public -/
def on_imported
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing staged _ =>
    if staged.slot <= bf.target_slot
    then
      let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Action) Action.Complete
      ok (out,
        {
          bf
            with
            frontier := staged,
            attempts := bf.cfg.max_attempts,
            wait := Wait.Idle,
            last_bad := none,
            done := true
        })
    else
      ok (alloc.vec.Vec.new Action,
        {
          bf
            with
            frontier := staged,
            attempts := bf.cfg.max_attempts,
            wait := Wait.Idle,
            last_bad := none
        })
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_rejected]:
    Source: 'common/backfill_core/src/lib.rs', lines 226:0-239:1
    Visibility: public -/
def on_rejected
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ peer =>
    let out ←
      alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Penalize peer)
    let bf1 ← retry { bf with last_bad := (some peer) }
    ok (out, bf1)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_fail]:
    Source: 'common/backfill_core/src/lib.rs', lines 241:0-253:1
    Visibility: public -/
def on_fail
  (bf : Backfill) (peer : Std.U32) :
  Result ((alloc.vec.Vec Action) × Backfill)
  := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending =>
    let bf1 ← retry { bf with last_bad := (some peer) }
    ok (alloc.vec.Vec.new Action, bf1)
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_peer_joined]:
    Source: 'common/backfill_core/src/lib.rs', lines 255:0-268:1
    Visibility: public -/
def on_peer_joined
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked =>
    ok (alloc.vec.Vec.new Action,
      {
        bf
          with
          attempts := bf.cfg.max_attempts, wait := Wait.Idle, last_bad := none
      })

/-- [backfill_core::step]:
    Source: 'common/backfill_core/src/lib.rs', lines 270:0-279:1
    Visibility: public -/
def step
  (bf : Backfill) (ev : Event) :
  Result ((alloc.vec.Vec Action) × Backfill)
  := do
  match ev with
  | Event.Tick => on_tick bf
  | Event.Run peer headers => on_run bf peer headers
  | Event.Fail peer => on_fail bf peer
  | Event.Imported => on_imported bf
  | Event.Rejected => on_rejected bf
  | Event.PeerJoined => on_peer_joined bf

/-- [backfill_core::from_anchor]:
    Source: 'common/backfill_core/src/lib.rs', lines 284:0-294:1
    Visibility: public -/
def from_anchor
  (cfg : Config) (oldest : Header) (target_slot : Std.U64) :
  Result Backfill
  := do
  ok
    {
      cfg,
      frontier := oldest,
      target_slot,
      attempts := cfg.max_attempts,
      wait := Wait.Idle,
      last_bad := none,
      done := (oldest.slot <= target_slot)
    }

end backfill_core
