-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [backfill_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace backfill_core

/-- [backfill_core::Root]
    Source: 'common/backfill_core/src/lib.rs', lines 41:0-46:1
    Visibility: public -/
structure Root where
  a : Std.U64
  b : Std.U64
  c : Std.U64
  d : Std.U64

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Root}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 40:9-40:14
    Visibility: public -/
def Root.Insts.CoreCloneClone.clone (self : Root) : Result Root := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Root}]
    Source: 'common/backfill_core/src/lib.rs', lines 40:9-40:14 -/
@[reducible]
def Root.Insts.CoreCloneClone : core.clone.Clone Root := {
  clone := Root.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Root}]
    Source: 'common/backfill_core/src/lib.rs', lines 40:16-40:20 -/
@[reducible]
def Root.Insts.CoreMarkerCopy : core.marker.Copy Root := {
  cloneInst := Root.Insts.CoreCloneClone
}

/-- Trait implementation: [backfill_core::{impl core::marker::StructuralPartialEq for backfill_core::Root}]
    Source: 'common/backfill_core/src/lib.rs', lines 40:22-40:31 -/
@[reducible]
def Root.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Root := {
}

/-- [backfill_core::{impl core::cmp::PartialEq<backfill_core::Root> for backfill_core::Root}::eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 40:22-40:31
    Visibility: public -/
def Root.Insts.CoreCmpPartialEqRoot.eq
  (self : Root) (other : Root) : Result Bool := do
  if self.a = other.a
  then
    if self.b = other.b
    then if self.c = other.c
         then ok (self.d = other.d)
         else ok false
    else ok false
  else ok false

/-- Trait implementation: [backfill_core::{impl core::cmp::PartialEq<backfill_core::Root> for backfill_core::Root}]
    Source: 'common/backfill_core/src/lib.rs', lines 40:22-40:31 -/
@[reducible]
def Root.Insts.CoreCmpPartialEqRoot : core.cmp.PartialEq Root Root := {
  eq := Root.Insts.CoreCmpPartialEqRoot.eq
}

/-- [backfill_core::{impl core::cmp::Eq for backfill_core::Root}::assert_fields_are_eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 40:33-40:35
    Visibility: public -/
def Root.Insts.CoreCmpEq.assert_fields_are_eq (self : Root) : Result Unit := do
  ok ()

/-- Trait implementation: [backfill_core::{impl core::cmp::Eq for backfill_core::Root}]
    Source: 'common/backfill_core/src/lib.rs', lines 40:33-40:35 -/
@[reducible]
def Root.Insts.CoreCmpEq : core.cmp.Eq Root := {
  partialEqInst := Root.Insts.CoreCmpPartialEqRoot
  assert_fields_are_eq := Root.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [backfill_core::root_eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 49:0-51:1
    Visibility: public -/
def root_eq (x : Root) (y : Root) : Result Bool := do
  ok (((x.a = y.a) && (x.b = y.b)) && ((x.c = y.c) && (x.d = y.d)))

/-- [backfill_core::Header]
    Source: 'common/backfill_core/src/lib.rs', lines 54:0-58:1
    Visibility: public -/
structure Header where
  root : Root
  parent_root : Root
  slot : Std.U64

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Header}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 53:9-53:14
    Visibility: public -/
def Header.Insts.CoreCloneClone.clone (self : Header) : Result Header := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 53:9-53:14 -/
@[reducible]
def Header.Insts.CoreCloneClone : core.clone.Clone Header := {
  clone := Header.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 53:16-53:20 -/
@[reducible]
def Header.Insts.CoreMarkerCopy : core.marker.Copy Header := {
  cloneInst := Header.Insts.CoreCloneClone
}

/-- Trait implementation: [backfill_core::{impl core::marker::StructuralPartialEq for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 53:22-53:31 -/
@[reducible]
def Header.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Header := {
}

/-- [backfill_core::{impl core::cmp::PartialEq<backfill_core::Header> for backfill_core::Header}::eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 53:22-53:31
    Visibility: public -/
def Header.Insts.CoreCmpPartialEqHeader.eq
  (self : Header) (other : Header) : Result Bool := do
  let b ← Root.Insts.CoreCmpPartialEqRoot.eq self.root other.root
  if b
  then
    let b1 ←
      Root.Insts.CoreCmpPartialEqRoot.eq self.parent_root other.parent_root
    if b1
    then ok (self.slot = other.slot)
    else ok false
  else ok false

/-- Trait implementation: [backfill_core::{impl core::cmp::PartialEq<backfill_core::Header> for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 53:22-53:31 -/
@[reducible]
def Header.Insts.CoreCmpPartialEqHeader : core.cmp.PartialEq Header Header := {
  eq := Header.Insts.CoreCmpPartialEqHeader.eq
}

/-- [backfill_core::{impl core::cmp::Eq for backfill_core::Header}::assert_fields_are_eq]:
    Source: 'common/backfill_core/src/lib.rs', lines 53:33-53:35
    Visibility: public -/
def Header.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Header) : Result Unit := do
  ok ()

/-- Trait implementation: [backfill_core::{impl core::cmp::Eq for backfill_core::Header}]
    Source: 'common/backfill_core/src/lib.rs', lines 53:33-53:35 -/
@[reducible]
def Header.Insts.CoreCmpEq : core.cmp.Eq Header := {
  partialEqInst := Header.Insts.CoreCmpPartialEqHeader
  assert_fields_are_eq := Header.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [backfill_core::Config]
    Source: 'common/backfill_core/src/lib.rs', lines 61:0-67:1
    Visibility: public -/
structure Config where
  run_len : Std.U64
  max_attempts : Std.U8

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Config}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 60:9-60:14
    Visibility: public -/
def Config.Insts.CoreCloneClone.clone (self : Config) : Result Config := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Config}]
    Source: 'common/backfill_core/src/lib.rs', lines 60:9-60:14 -/
@[reducible]
def Config.Insts.CoreCloneClone : core.clone.Clone Config := {
  clone := Config.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Config}]
    Source: 'common/backfill_core/src/lib.rs', lines 60:16-60:20 -/
@[reducible]
def Config.Insts.CoreMarkerCopy : core.marker.Copy Config := {
  cloneInst := Config.Insts.CoreCloneClone
}

/-- [backfill_core::Wait]
    Source: 'common/backfill_core/src/lib.rs', lines 73:0-83:1
    Visibility: public -/
@[discriminant isize]
inductive Wait where
| Idle : Wait
| Pending : Wait
| Importing : Header → Std.U32 → Wait
| Parked : Wait

/-- [backfill_core::{impl core::clone::Clone for backfill_core::Wait}::clone]:
    Source: 'common/backfill_core/src/lib.rs', lines 72:9-72:14
    Visibility: public -/
def Wait.Insts.CoreCloneClone.clone (self : Wait) : Result Wait := do
  ok self

/-- Trait implementation: [backfill_core::{impl core::clone::Clone for backfill_core::Wait}]
    Source: 'common/backfill_core/src/lib.rs', lines 72:9-72:14 -/
@[reducible]
def Wait.Insts.CoreCloneClone : core.clone.Clone Wait := {
  clone := Wait.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [backfill_core::{impl core::marker::Copy for backfill_core::Wait}]
    Source: 'common/backfill_core/src/lib.rs', lines 72:16-72:20 -/
@[reducible]
def Wait.Insts.CoreMarkerCopy : core.marker.Copy Wait := {
  cloneInst := Wait.Insts.CoreCloneClone
}

/-- [backfill_core::Backfill]
    Source: 'common/backfill_core/src/lib.rs', lines 85:0-96:1
    Visibility: public -/
structure Backfill where
  cfg : Config
  frontier : Header
  target_slot : Std.U64
  attempts : Std.U8
  wait : Wait
  last_bad : Option Std.U32
  done : Bool

/-- [backfill_core::Event]
    Source: 'common/backfill_core/src/lib.rs', lines 101:0-120:1
    Visibility: public -/
@[discriminant isize]
inductive Event where
| Tick : Event
| Run : Std.U32 → alloc.vec.Vec Header → Event
| Fail : Option Std.U32 → Event
| Imported : Event
| Rejected : Event
| Abandoned : Event
| PeerJoined : Event

/-- [backfill_core::Action]
    Source: 'common/backfill_core/src/lib.rs', lines 122:0-135:1
    Visibility: public -/
@[discriminant isize]
inductive Action where
| Request : Root → Std.U64 → Option Std.U32 → Action
| Store : alloc.vec.Vec Header → Action
| Penalize : Std.U32 → Action
| Complete : Action

/-- [backfill_core::check_run]: loop 0:
    Source: 'common/backfill_core/src/lib.rs', lines 152:4-161:5
    Visibility: public -/
@[rust_loop]
def check_run_loop
  (headers : alloc.vec.Vec Header) (linked : Bool) (want : Root)
  (limit : Std.U64) (last : Option Header) (i : Std.Usize) :
  Result (Bool × (Option Header))
  := do
  let i1 := alloc.vec.Vec.len headers
  if i < i1
  then
    let header ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Header)
        headers i
    let b ← root_eq header.root want
    let i2 ← i + 1#usize
    check_run_loop headers ((linked && b) && (header.slot < limit))
      header.parent_root header.slot (some header) i2
  else ok (linked, last)
partial_fixpoint

/-- [backfill_core::check_run]:
    Source: 'common/backfill_core/src/lib.rs', lines 146:0-163:1
    Visibility: public -/
def check_run
  (expected : Root) (bound : Std.U64) (headers : alloc.vec.Vec Header) :
  Result (Option Header)
  := do
  let (linked, last) ←
    check_run_loop headers true expected bound none 0#usize
  if linked
  then ok last
  else ok none

/-- [backfill_core::retry]:
    Source: 'common/backfill_core/src/lib.rs', lines 168:0-176:1
    Visibility: public -/
def retry (bf : Backfill) : Result Backfill := do
  if bf.attempts > 1#u8
  then
    let i ← bf.attempts - 1#u8
    ok { bf with attempts := i, wait := Wait.Idle }
  else ok { bf with attempts := 0#u8, wait := Wait.Parked }

/-- [backfill_core::on_tick]:
    Source: 'common/backfill_core/src/lib.rs', lines 178:0-197:1
    Visibility: public -/
def on_tick (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle =>
    if bf.done
    then ok (alloc.vec.Vec.new Action, bf)
    else
      let out ←
        alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Request
          bf.frontier.parent_root bf.cfg.run_len bf.last_bad)
      ok (out, { bf with wait := Wait.Pending })
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_run]:
    Source: 'common/backfill_core/src/lib.rs', lines 199:0-224:1
    Visibility: public -/
def on_run
  (bf : Backfill) (peer : Std.U32) (headers : alloc.vec.Vec Header) :
  Result ((alloc.vec.Vec Action) × Backfill)
  := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending =>
    let checked ← check_run bf.frontier.parent_root bf.frontier.slot headers
    match checked with
    | none =>
      let out ←
        alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Penalize peer)
      let bf1 ← retry { bf with last_bad := (some peer) }
      ok (out, bf1)
    | some oldest =>
      let out ←
        alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Store headers)
      ok (out, { bf with wait := (Wait.Importing oldest peer) })
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_imported]:
    Source: 'common/backfill_core/src/lib.rs', lines 229:0-247:1
    Visibility: public -/
def on_imported
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing staged _ =>
    if staged.slot <= bf.target_slot
    then
      let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Action) Action.Complete
      ok (out,
        {
          bf
            with
            frontier := staged,
            attempts := bf.cfg.max_attempts,
            wait := Wait.Idle,
            last_bad := none,
            done := true
        })
    else
      ok (alloc.vec.Vec.new Action,
        {
          bf
            with
            frontier := staged,
            attempts := bf.cfg.max_attempts,
            wait := Wait.Idle,
            last_bad := none
        })
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_rejected]:
    Source: 'common/backfill_core/src/lib.rs', lines 252:0-265:1
    Visibility: public -/
def on_rejected
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ peer =>
    let out ←
      alloc.vec.Vec.push (alloc.vec.Vec.new Action) (Action.Penalize peer)
    let bf1 ← retry { bf with last_bad := (some peer) }
    ok (out, bf1)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_abandoned]:
    Source: 'common/backfill_core/src/lib.rs', lines 269:0-281:1
    Visibility: public -/
def on_abandoned
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ peer =>
    let bf1 ← retry { bf with last_bad := (some peer) }
    ok (alloc.vec.Vec.new Action, bf1)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_fail]:
    Source: 'common/backfill_core/src/lib.rs', lines 283:0-295:1
    Visibility: public -/
def on_fail
  (bf : Backfill) (peer : Option Std.U32) :
  Result ((alloc.vec.Vec Action) × Backfill)
  := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending =>
    let bf1 ← retry { bf with last_bad := peer }
    ok (alloc.vec.Vec.new Action, bf1)
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked => ok (alloc.vec.Vec.new Action, bf)

/-- [backfill_core::on_peer_joined]:
    Source: 'common/backfill_core/src/lib.rs', lines 297:0-310:1
    Visibility: public -/
def on_peer_joined
  (bf : Backfill) : Result ((alloc.vec.Vec Action) × Backfill) := do
  match bf.wait with
  | Wait.Idle => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Pending => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Importing _ _ => ok (alloc.vec.Vec.new Action, bf)
  | Wait.Parked =>
    ok (alloc.vec.Vec.new Action,
      {
        bf
          with
          attempts := bf.cfg.max_attempts, wait := Wait.Idle, last_bad := none
      })

/-- [backfill_core::step]:
    Source: 'common/backfill_core/src/lib.rs', lines 312:0-322:1
    Visibility: public -/
def step
  (bf : Backfill) (ev : Event) :
  Result ((alloc.vec.Vec Action) × Backfill)
  := do
  match ev with
  | Event.Tick => on_tick bf
  | Event.Run peer headers => on_run bf peer headers
  | Event.Fail peer => on_fail bf peer
  | Event.Imported => on_imported bf
  | Event.Rejected => on_rejected bf
  | Event.Abandoned => on_abandoned bf
  | Event.PeerJoined => on_peer_joined bf

/-- [backfill_core::from_anchor]:
    Source: 'common/backfill_core/src/lib.rs', lines 327:0-337:1
    Visibility: public -/
def from_anchor
  (cfg : Config) (oldest : Header) (target_slot : Std.U64) :
  Result Backfill
  := do
  ok
    {
      cfg,
      frontier := oldest,
      target_slot,
      attempts := cfg.max_attempts,
      wait := Wait.Idle,
      last_bad := none,
      done := (oldest.slot <= target_slot)
    }

end backfill_core
