[package]
name = "proof_seeder"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
axum = { workspace = true }
eth2 = { workspace = true }
sensitive_url = { workspace = true }
eth2_keystore = { workspace = true }
bls = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tree_hash = { workspace = true }
types = { workspace = true }
